# Site settings
title: Cristi Scheye Homesite
email: cristi.scheye@gmail.com
url: "http://cristischeye.com" # the base hostname & protocol for your site
github_username:  cristischeye
encoding: utf-8
